{% set version = "0.4.0" %}

package:
  name: pyepsg
  version: {{ version }}

source:
  url: https://github.com/rhattersley/pyepsg/archive/v{{ version }}.tar.gz
  sha256: 2737302c3661464a867d1844ab1adab046ccbf763edd54140811e21238894f05

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - pyepsg

about:
  home: https://pypi.python.org/pypi/pyepsg
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Easy access to the EPSG database via http://epsg.io/'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
