{% set version = "0.4.0" %}

package:
  name: pyepsg
  version: {{ version }}

source:
  url: https://github.com/rhattersley/pyepsg/archive/v{{ version }}.tar.gz
  sha256: 8e65ba011175630f8ffae55dae5486a81fb3484c1c0af236a4af3ffac6ed4f86

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - pyepsg

about:
  home: https://pypi.python.org/pypi/pyepsg
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Easy access to the EPSG database via http://epsg.io/'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
